DROP SEQUENCE BOARDNOSEQ;
DROP TABLE BOARD;

CREATE SEQUENCE BOARDNOSEQ;

CREATE TABLE BOARD(
	BOARD_NO NUMBER NOT NULL PRIMARY KEY,
	BOARD_CATEGORY VARCHAR2(30) NOT NULL CHECK (BOARD_CATEGORY IN ('공지','문의', '신고')),
	BOARD_MAIN_ID VARCHAR2(30) NOT NULL,
	BOARD_MAIN_TITLE VARCHAR2(30) NOT NULL,
	BOARD_MAIN_CONTENT LONG NOT NULL,
	BOARD_MAIN_DATE DATE NOT NULL,
	BOARD_MAIN_VIEWS NUMBER,
	BOARD_MAIN_SECRET VARCHAR2(5),
	BOARD_MAIN_FILEID VARCHAR2(500),
	CONSTRAINT BOARD_MAIN_ID_FK FOREIGN KEY(BOARD_MAIN_ID) REFERENCES MEMBER(MEMBER_ID)
);

select * from board;

alter table board add BOARD_MAIN_FILELOC VARCHAR2(3000);




update board set board_main_views = 0;

DROP SEQUENCE REPLYNOSEQ;
DROP TABLE REPLY;

CREATE SEQUENCE REPLYNOSEQ;

CREATE TABLE REPLY(
	REPLY_NO NUMBER NOT NULL PRIMARY KEY,                                 
	BOARD_NO NUMBER NOT NULL REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,                   
	BOARD_CATEGORY VARCHAR2(30) NOT NULL CHECK (BOARD_CATEGORY IN ('문의', '신고')), 
	REPLY_ID VARCHAR2(30) NOT NULL REFERENCES MEMBER(MEMBER_ID),          
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,                                 
	REPLY_DATE DATE NOT NULL              
);

select * from reply;

ALTER TABLE BOARD
DROP CONSTRAINT BOARD_MAIN_ID_FK;
ALTER TABLE BOARD ADD CONSTRAINT BOARD_MAIN_ID_FK FOREIGN KEY (BOARD_MAIN_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE;