
DROP TABLE CATEGORY;

CREATE TABLE CATEGORY(
	CATEGORY_NUM NUMBER NOT NULL PRIMARY KEY,
	CATEGORY_TYPE VARCHAR2(5) CHECK (CATEGORY_TYPE IN ('M', 'S')),
	CATEGORY_NAME VARCHAR2(15) NOT NULL
);

INSERT INTO CATEGORY
VALUES(1, 'M', 'IT');

INSERT INTO CATEGORY
VALUES(2, 'M', '교과목');

INSERT INTO CATEGORY
VALUES(3, 'M', '미용/뷰티');

INSERT INTO CATEGORY
VALUES(4, 'M', '언어');

INSERT INTO CATEGORY
VALUES(5, 'M', '요리');

INSERT INTO CATEGORY
VALUES(6, 'M', '자격증');

INSERT INTO CATEGORY
VALUES(7, 'M', '기타');

select * from category;