DROP TABLE PAYMENT;
DROP SEQUENCE PAYMENT_NO;

CREATE SEQUENCE PAYMENT_NO;

CREATE TABLE PAYMENT(
	PAYMENT_NO NUMBER NOT NULL PRIMARY KEY,
 	BUYER_ID VARCHAR2(30) NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	BUYER_TEL VARCHAR2(50) NOT NULL,
	CLASS_NO NUMBER NOT NULL REFERENCES UPLOAD(UPLOAD_NO) ON DELETE CASCADE,
	SELLER_ID VARCHAR2(100) NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	CLASS_TITLE VARCHAR2(200) NOT NULL,
	CLASS_VIDEO VARCHAR2(4000) NOT NULL,
	CLASS_PRICE NUMBER NOT NULL,
	CLASS_CATEGORY NUMBER NOT NULL,
	BUY_DATE DATE NOT NULL
);

SELECT * FROM PAYMENT

