DROP SEQUENCE UPLOAD_NO;
DROP TABLE UPLOAD;

CREATE SEQUENCE UPLOAD_NO;
CREATE TABLE UPLOAD(
	UPLOAD_NO NUMBER NOT NULL PRIMARY KEY,
	UPLOAD_ID VARCHAR2(100) NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	UPLOAD_TITLE VARCHAR2(3000) NOT NULL,
	UPLOAD_CATEGORY NUMBER NOT NULL REFERENCES CATEGORY(CATEGORY_NUM) ON DELETE CASCADE,
	UPLOAD_PRICE NUMBER NOT NULL,
	UPLOAD_CONTENT LONG,
	UPLOAD_FILE_NAME VARCHAR2(4000) NOT NULL,
	UPLOAD_FILE_LOC VARCHAR2(4000),
	UPLOAD_DATE DATE NOT NULL
);

select * FROM UPLOAD;

delete from upload;