-- Video 방 생성
DROP SEQUENCE VIDEONOSEQ;
DROP TABLE VIDEOROOMS;

CREATE SEQUENCE VIDEONOSEQ;

CREATE TABLE VIDEOROOMS(
	ROOM_NO NUMBER PRIMARY KEY,
	ROOM_ID VARCHAR2(1000) NOT NULL,
	ROOM_TITLE VARCHAR2(1000) NOT NULL,
	MENTOR_ID VARCHAR2(1000) NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	MENTEE_ID VARCHAR2(1000) NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	CREATE_DATE DATE NOT NULL
);

SELECT ROOM_NO, ROOM_ID, ROOM_TITLE, MENTOR_ID, MENTEE_ID, CREATE_DATE FROM VIDEOROOMS ORDER BY CREATE_DATE DESC;

DELETE FROM VIDEOROOMS WHERE MENTORID = 'mentor1';